Repository squid-cache/squid, pull requests merged in 2024-10, with the labels that each got.

#1911 v6 Next Backports
  src/auth/digest/Config.cc
Labels: M-cleared-for-merge

#1909 ext_time_quota_acl: remove -l option
  doc/release-notes/release-6.sgml.in
  src/acl/external/time_quota/ext_time_quota_acl.8
  src/acl/external/time_quota/ext_time_quota_acl.cc
Labels: M-waiting-staging-checks

#1925 Maintenance: Add missing ChangeLog separators
  ChangeLog
Labels: S-waiting-for-author, S-could-use-an-approval
